# Ejemplo: Nginx y Spring Boot en el mismo servidor.
# Cambia root por la ubicación REAL del directorio browser compilado.
server {
    listen 80;
    server_name localhost;
    root /var/www/cliente-angular-graphdb/browser;
    index index.html;
    location /api/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 60s;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
